# Generated by Django 6.0 on 2025-12-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='execution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
